### ISSUE TITLE
workspace() does not work as intented in Juno+Atom console

### ISSUE THREAD

**Issue by Datseris** [JunoLab/Atom.jl#78]
example code from the console:
```julia
using Distributions;
workspace();
using Distributions

WARNING: Method definition 
redirect_stderr(Function, Any) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615.
WARNING: Method definition isnull(Any) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1693 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1693.
WARNING: Method definition take!(Main.Base.AbstractIOBuffer) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1713 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1713.
WARNING: Method definition redirect_stdin(Function, Any) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615.
WARNING: Method definition !(Function) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1746 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1746.
WARNING: Method definition redirect_stdout(Function, Any) in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615 overwritten in module Compat at C:\Users\migos\.julia\v0.5\Compat\src\Compat.jl:1615.
WARNING: Method definition quantile(AbstractArray{#T<:Real, N<:Any}) in module StatsBase at C:\Users\migos\.julia\v0.5\StatsBase\src\scalarstats.jl:213 overwritten in module StatsBase at C:\Users\migos\.julia\v0.5\StatsBase\src\scalarstats.jl:213.
.
.
.
```
The list of warnings goes on and on and... You get the point!
Notice: This happens for ALL packages and for user defined functions. So pretty much `workspace()` does not work.
I actually encountered this problem when I was trying to make my own shortcut for "restart console and run file" .But this shows that in generally workspace has problems (I guess).

**Comment by pfitzseb** [comment]
Hm, this isn't specific to Juno -- I get the same behaviour in the REPL too.

**Comment by ChrisRackauckas** [comment]
I think this was just related to #265, and got fixed in v0.6. Right?

**Comment by pfitzseb** [comment]
Nope, I still get deprecation warnings on 0.6; but the same happens in the REPL too, so I'll close this one.
